### ISSUE TITLE
[UI Fix] Warn when overwriting a pending device entry

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#45]
I can only have one device in "pending" state (where the MAC address is unassigned until the device connects) at a time. If I try to add another one, it silently replaces the first.

It should be possible to have multiple pending devices because they will connect with different passwords and therefore can be differentiated.

**Comment by lts-rad** [comment]
This is a limitation of WPA3 support and using the wildcard MAC to accept a new device without knowing it's MAC address. ahead of time. When a device does authenticate successfully, the "pending" identifier is assigned to that device's MAC address.

Essentially -- WPA3 is a zero knowledge authentication protocol. The server must know the same password as the client ahead of time, otherwise the server has to have the client reconnect and retry if the server guesses the wrong password. So only one password at a time can be used with the password assigned to the wildcard MAC.

This differs from WPA2 where it would be possible to run multiple PBKDF2 hashes to find a matching password.

As a work around, a user can specify the MAC address of multiple new devices before they connect.

Docs might need to better reflect this

**Comment by rgov** [comment]
Thanks for context. I think not only docs but a UI alert should appear and get confirmation before proceeding to delete a previously configured host.

**Comment by lts-po** [comment]
fixed in dev https://github.com/spr-networks/super/commit/15bfa142967548920d250de7aa914a8a04bfb70b
