### ISSUE TITLE
Avoid confusable characters in generated passwords

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#52]
I got a password that contained the substring `1l`, which are hard to differentiate when displayed in a proportional font (e.g., if sent over a messaging app).

It would be good to consider password ergonomics generally. E.g., the `uavpxq-ehthib-estutw-tlniyx-qzsizv` style is easier to type on a phone keyboard, requiring few switches to the numeric/symbol keys. On the other hand with something like a printer this might be more tedious.

**Comment by 0vercl0k** [comment]
I ran into something similar today; the below highlighted character was totally not what I thought it was; I don't quite remember what it ended up being but it might have been a 1 although it looks more like a uppercase i. I grabbed a snapshot so that you guys can debug:

![signal-2023-06-01-074905_002](https://github.com/spr-networks/super/assets/1476421/2d9f6503-0731-4144-9c17-e574d49eecef)

**Comment by lts-po** [comment]
The updated genSecurePassword now avoids 1l, O0 etc.
